[project]
name = "sis-leg-device-bridge"
version = "0.0.0"
description = "Bridge físico Linux y compatibilidad de dispositivos para SIS-Leg"
requires-python = ">=3.14,<3.15"
dependencies = [
    "evdev>=1.9.3,<2",
]

[project.scripts]
sis-leg-device-bridge = "sis_leg_device_bridge.cli:ejecutar_cli"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
